# Generated by Django 4.2.7 on 2023-11-22 13:55

import Server.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveryman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sur_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Телефон')),
                ('patronymic', models.CharField(blank=True, max_length=20, verbose_name='Отчество')),
                ('lates_count', models.IntegerField(default='0', verbose_name='Количество опозданий')),
                ('orders_count', models.IntegerField(default='0', verbose_name='Количество доставленных заказов')),
                ('photo', models.ImageField(blank=True, upload_to=Server.models.user_directory_path, verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.TextField(max_length=150, verbose_name='Адрес доставки')),
                ('coment', models.TextField(max_length=300, verbose_name='Комментарий к заказу')),
                ('client_number', models.CharField(max_length=12, verbose_name='Телефон заказчика')),
                ('deliveryman_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Server.deliveryman', verbose_name='Курьер')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Server.deliverystatus', verbose_name='Статус'),
        ),
    ]
