# Generated by Django 4.2.7 on 2023-12-28 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveryman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sur_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Телефон')),
                ('patronymic', models.CharField(blank=True, max_length=20, verbose_name='Отчество')),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lates_count', models.IntegerField(default='0', verbose_name='Количество опозданий')),
                ('orders_count', models.IntegerField(default='0', verbose_name='Количество доставленных заказов')),
                ('sum_time', models.IntegerField(verbose_name='Сумма времени потраченного на заказы')),
                ('time_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='TypePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.TextField(max_length=150, verbose_name='Улица Дом')),
                ('dop_adres', models.TextField(max_length=150, verbose_name='Подъезд/этаж/квартира')),
                ('cost', models.FloatField()),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('time_limit', models.CharField(max_length=5)),
                ('coment', models.TextField(blank=True, max_length=300, verbose_name='Комментарий к заказу')),
                ('client_number', models.CharField(max_length=12, verbose_name='Телефон заказчика')),
                ('deliveryman_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Server.deliveryman', verbose_name='Курьер')),
                ('status', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='Server.orderstatus', verbose_name='Статус заказа')),
                ('type_pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Server.typepay')),
            ],
        ),
    ]
